### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by lgarest** [pablobuenaposada/fitbot#1]
Can't book the next appointment

Error traceback
```
python client.py
Traceback (most recent call last):
  File "/Users/luis/dev/fitbot/main.py", line 23, in <module>
    goal_time = goal.get(target_day_of_the_week, None)
AttributeError: 'int' object has no attribute 'get'
```
settings.py
```
BOOKING_GOALS = {
    0: '1730',  # Mondays at 17:30
    2: '1730',  # Wednesdays at 17:30
}
```

**Comment by pablobuenaposada** [comment]
You are running old version of Fitbot, please update

**Comment by lgarest** [comment]
Issue updated

**Comment by pablobuenaposada** [comment]
still see weird code, I guess you are doing `python main.py` instead of `python client.py`
BOOKING_GOALS is not a dict anymore but I still see it in your comment, that's probably the issue

**Comment by lgarest** [comment]
Indeed, thanks! 👍
