### ISSUE TITLE
exec /usr/bin/make: exec format error

### ISSUE THREAD

**Issue by PozoSer** [pablobuenaposada/fitbot#20]
Hi there, 

Thanks for doing this idea. I have tried deploying this on Portainer but I get the exec format error. This is my config of the env variables:

![image](https://user-images.githubusercontent.com/18380820/201425774-2901f211-db13-4292-82de-4cc8885fe119.png)

Thanks in advance

**Comment by PozoSer** [comment]
I'm trying to run this on a raspberry, btw.

**Comment by pablobuenaposada** [comment]
can you share the full error stacktrace?

**Comment by PozoSer** [comment]
On the raspberry I dont get anything else, only "exec /usr/bin/make: exec format error"

If I try to run it on a x86 machine I get through to the following error:

main.py: error: argument --booking-goals: invalid loads value: '{1:'

**Comment by pablobuenaposada** [comment]
there you have it, `booking-goals` it's not well formatted, check the readme, there's an example on how to correctly scape it

**Comment by PozoSer** [comment]
Finally got it working, yeah!

Quick doubt, how does the reservation work? The software queries the website on the specific time - delta (days-in-advance) and tries until it get either an error or a success?

**Comment by pablobuenaposada** [comment]
no, the project is going to try only one time when you run it, it's on you to schedule it whenever you want

**Comment by PozoSer** [comment]
I see. Wouldn't it make sense to use the booking goals to auto run the software automatically? And improve chances of getting a spot on a class.

**Comment by pablobuenaposada** [comment]
then the project needs to be alive 24/7, can be done? yes, is it way more complex? yes.
If you know when the class is open for registration you can run this script at the same exact time, more chances than in that situation you cannot have, and then to have the rest of the day the project alive is useless.
